export const ACTION_NAMES = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    GET_ALL_USERS_INFO: "GET_ALL_USERS_INFO",
    GET_ALL_USERS_INFO_SUCCESS: "GET_ALL_USERS_INFO_SUCCESS",
    GET_ALL_USERS_INFO_ERROR: "GET_ALL_USERS_INFO_ERROR",
    GET_ACCOUNT_INFO: "GET_ACCOUNT_INFO",
    GET_ACCOUNT_INFO_SUCCESS: "GET_ACCOUNT_INFO_SUCCESS",
    GET_ACCOUNT_INFO_ERROR: "GET_ACCOUNT_INFO_ERROR",
};
