export const GET_ALL_TODO = 'GET_ALL_TODO'
export const GET_ALL_TODO_SUCCEED = 'GET_ALL_TODO_SUCCEED'

export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_SUCCEED = 'ADD_TODO_SUCCEED'

export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_TODO_SUCCEED= 'UPDATE_TODO_SUCCEED'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_SUCCEED = 'DELETE_TODO_SUCCEED'