export const SAGA_NAMES = {
    SAGA_GET_LIST_TODO_SUCCESS: "SAGA_GET_LIST_TODO_SUCCESS",
    SAGA_ADD_TODO_SUCCESS: "SAGA_ADD_TODO_SUCCESS",
    SAGA_TOGGLE_TODO_SUCCESS: "SAGA_TOGGLE_TODO_SUCCESS",
    SAGA_REMOVE_TODO_SUCCESS: "SAGA_REMOVE_TODO_SUCCESS",
};
