export const TodoStyle = {
    todoPageContainer: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "center",
    },
    todoListWrapper: {
        display: "flex",
        width: 1000,
        alignItems: "center",
        flexDirection: "column",
    },
    todoListContainer: {
        display: "flex",
        width: 700,
        justifyContent: "center",
    },
    todoListTitleWrapper: {
        width: 600,
        borderBottomWidth: 1.5,
        borderBottomStyle: "solid",
        borderBottomColor: "#e0e0e0",
    },
    todoItemWrapper: {
        height: 55,
        borderBottomStyle: "solid",
        borderBottomColor: "#e0e0e0",
        borderBottomWidth: 1.3,
        display: "flex",
        flexDirection: "row",
    },
    checkBoxWrapper: {
        width: 570 * 0.05,
        display: "flex",
        alignItems: "flex-end",
        justifyContent: "center",
    },
    contentWrapper: {
        width: 570 * 0.9,
        display: "flex",
        alignItems: "flex-end",
        justifyItems: "center",
    },
    removeButtonWrapper: {
        width: 570 * 0.05,
        display: "flex",
        alignItems: "flex-end",
        justifyItems: "center",
    },
    removeButton: {
        marginBottom: 12,
        height: 26,
        borderStyle: "solid",
        borderWidth: 0.75,
        borderColor: "#aba9a9",
    },
    todoFormWrapper: {
        display: "flex",
        height: 100,
        width: 700,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
    },
    todoInputWraper: {
        height: 37,
        width: 500,
        borderRadius: 5,
        borderStyle: "none",
        backgroundColor: "#ffff",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    addTodoButton: {
        height: 39,
        width: 100,
        marginLeft: 5,
        borderRadius: 3,
        borderStyle: "none",
        backgroundColor: "#125acc",
        color: "#fff",
        outline: "none",
    },
    todoInput: {
        height: 35,
        width: 470,
        borderStyle: "none",
        marginLeft: 5,
        outline: "none",
    },
};
