export const ACTION_NAMES = {
    GET_ALL_TODO_LIST: "GET_ALL_TODO_LIST",
    ADD_TODO: "ADD_TODO",
    DELETE_TODO: "DELETE_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    SHOW_COMPLETED: "SHOW_COMPLETED",
    SEARCH_TODO: "SEARCH_TODO",
};
