//Status of Add/Udate form
export const OPEN_FORM = 'OPEN_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';

//Get item
export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

//Add item
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';


//Update item
export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';
//Get item wanna to editing
export const GET_ITEM_EDITING = 'GET_ITEM_EDITING';


//Delete item
export const DELETE_ITEM_REQUEST = 'DELELE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELELE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELELE_ITEM_FAILURE';

//Update status of item
export const UPDATE_STATUS_ITEM_REQUEST = 'UPDATE_STATUS_ITEM_REQUEST';
export const UPDATE_STATUS_ITEM_SUCCESS = 'UPDATE_STATUS_ITEM_SUCCESS';
export const UPDATE_STATUS_ITEM_FAILURE = 'UPDATE_STATUS_ITEM_FAILURE';
